name: Remote Dispatch Event Responder

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [pr-deploy-staging]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # latest LTS
    
    steps:
    - name: Event Handle - Execute the deployment process
      uses: actions/checkout@v2
      with:
        # Repository name with owner. For example, actions/checkout
        repository: 'lambdulus/frontend'
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm ci
        REACT_APP_VERSION_INFO=$(date +"%m-%d-%y-%T") REACT_APP_COMMIT=$(git rev-parse HEAD) PUBLIC_URL=https://lambdulus.github.io/staging/${{ github.event.client_payload.branch }} npm run build --if-present
    - name: Checkout the current repo
      uses: actions/checkout@v2
      with:
        path: 'staging'
    - run: |
        rm -rf ./staging/${{ github.event.client_payload.branch }}
        mkdir ./staging/${{ github.event.client_payload.branch }}
        mv ./build/* ./staging/${{ github.event.client_payload.branch }}/
    - run: |
        cd ./staging/${{ github.event.client_payload.branch }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "deploy"
        git push
