name: Remote Dispatch Event Responder

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [pr-purge-staging]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v2
    - run: |
        rm -rf ./pr/${{ github.event.client_payload.branch }}
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "purging"
        git push
